### ISSUE TITLE
Remove `background-color` from tab

### ISSUE THREAD

**Issue by stevepiercy** [collective/sphinxcontrib-httpexample#107]
When using a theme in dark mode, the background color of the tab makes it illegible.

![Screenshot 2024-09-19 at 5 26 39 PM](https://github.com/user-attachments/assets/347a9186-5dfa-4c0d-91c4-da3da14854d5)

This is due to the CSS:

```css
.http-example .caption.selected {
  background-color: #fff;
}
```

To work around this issue, I added a custom style to Plone Sphinx Theme in https://github.com/plone/plone-sphinx-theme/pull/28.

```css
.http-example .caption.selected {
  background-color: unset;
}
```

![Screenshot 2024-09-19 at 5 30 39 PM](https://github.com/user-attachments/assets/80e0e8d3-3922-41ea-9985-527e8a10521c)

However, I can see why you would want to set the background color for themes that have a light grey content background, such as Read The Docs Sphinx Theme.

![Screenshot 2024-09-19 at 5 29 52 PM](https://github.com/user-attachments/assets/7c593f24-ff28-4378-b854-ba69d0be0536)

Here's how it would look, and the difference is negligible.

![Screenshot 2024-09-19 at 5 29 21 PM](https://github.com/user-attachments/assets/2ee55402-afbe-4242-b308-224308dc374d)

If you think this would be a good improvement, I can submit a PR.

See also https://github.com/plone/plone.restapi/pull/1815
